# -*- coding: utf-8 -*-
"""majorproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcUSGrVWJB10FUcgLQPRY0wsm32ThllH
"""

import requests

url = "https://pmkisan.gov.in/MapFile/a.json"

try:
    response = requests.get(url, timeout=10)  # 10-second timeout
    response.raise_for_status()  # Raise error for bad response
    data = response.json()
    print(data)  # JSON data print karega
except requests.exceptions.Timeout:
    print("Request timed out! Server might be down.")
except requests.exceptions.RequestException as e:
    print(f"Error: {e}")

import requests

url = "https://www.india.gov.in/news_feeds?rand=1742633241721"
response = requests.get(url)

print("Content-Type:", response.headers.get("Content-Type"))
print("Response Data:", response.text[:500])  # Pehle 500 characters dikhaye

import requests
from bs4 import BeautifulSoup

url = "https://www.india.gov.in/news_feeds?rand=1742633241721"
headers = {"User-Agent": "Mozilla/5.0"}  # Server block na kare

response = requests.get(url, headers=headers)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")

    # Sabhi news links extract karein
    news_items = soup.find_all("li", class_="views-row")

    for news in news_items:
        title = news.find("a").text.strip()  # News title
        link = news.find("a")["href"]  # News link
        print(f"📰 {title}: {link}")
else:
    print("❌ Failed to fetch news data!")

import csv

with open("news_data.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["Title", "Link"])  # Headers

    for news in news_items:
        title = news.find("a").text.strip()
        link = news.find("a")["href"]
        writer.writerow([title, link])

print("✅ News data saved as news_data.csv!")

import requests
import json

# API Endpoint
url = "https://www.myscheme.gov.in/_next/data/k2wKKYodFQh7wrnE6ipEc/en/schemes/fadsp1012e.json"

# Fetch Data
response = requests.get(url)

if response.status_code == 200:
    data = response.json()

    # Display all available schemes
    print(json.dumps(data, indent=4))  # Pretty-print JSON response
else:
    print("Failed to fetch data. Status Code:", response.status_code)

import json

# JSON File ko Read karna
with open("pmkisan_data.json", "r", encoding="utf-8") as file:
    data = json.load(file)

# JSON ka structure samajhne ke liye first 5 elements print karein
print(json.dumps(data, indent=4))

import json

# JSON File Load Karna
with open("pmkisan_data.json", "r", encoding="utf-8") as file:
    data = json.load(file)

# Features ke andar ka data extract karna
features = data.get("features", [])

# State-wise data store karne ke liye dictionary
state_data = {}

# Har feature ko check karna
for feature in features:
    properties = feature.get("properties", {})
    state_name = properties.get("STNAME", "Unknown")
    state_code = properties.get("STCODE11", "Unknown")

    # Data ko store karna
    state_data[state_name] = {
        "State Code": state_code,
        "LGD Code": properties.get("State_LGD", "Unknown")
    }

# Extracted Data Print Karna
for state, details in state_data.items():
    print(f"State: {state}")
    print(f"  State Code: {details['State Code']}")
    print(f"  LGD Code: {details['LGD Code']}")
    print("-" * 40)

import requests
import json

# API Endpoint (Replace with actual API URL)
api_url = "https://api.data.gov.in/resource/62c17dfe-27ad-466b-9750-89ca736b1211"  # Replace 'xxxxxxx' with actual resource ID

# Your API Key
api_key = "579b464db66ec23bdd000001dfa1867f338c4c336e6dc11014b5d316"  # Replace with your actual API key

# Query Parameters (Modify based on requirements)
params = {
    "api-key": api_key,
    "format": "json",  # Fetch data in JSON format
    "limit": 100  # Number of records to fetch
}

# Make API Request with a longer timeout
try:
    response = requests.get(api_url, params=params, timeout=30)  # Increased timeout to 30 seconds
    # Check Response Status
    if response.status_code == 200:
        data = response.json()  # Convert response to JSON

        # Pretty Print JSON Response
        print(json.dumps(data, indent=4))

        # Extract required fields (Example)
        records = data.get("records", [])
        for record in records:
            print(f"State: {record.get('state')}, Trained Candidates: {record.get('trained_candidates')}")
    else:
        print("Error:", response.status_code, response.text)
except requests.exceptions.Timeout:
    print("Request timed out! The server might be down or overloaded.")
except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")

import json

# Load JSON file
with open("/content/pmkvy_data.json", "r", encoding="utf-8") as file:
    data = json.load(file)

# Display JSON data
print(json.dumps(data, indent=4))

import json

# Load the JSON file
with open("/content/pmkvy_data.json", "r", encoding="utf-8") as file:
    data = json.load(file)

# Print the keys to understand the structure
print(data.keys())

print(data["records"][0].keys())  # Print first record's keys





